# Generated by Django 3.2.9 on 2021-11-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('log', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'model_log',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stopSellPercentage', models.IntegerField()),
            ],
            options={
                'db_table': 'model_stocksell',
            },
        ),
    ]
